require('./array.spec');
require('./number.spec');
require('./validator.spec');
require('./pattern.spec');
require('./string.spec');
require('./url.spec');
require('./date.spec');
require('./messages.spec');
require('./deep.spec');
